### ISSUE TITLE
Weird Crash in version 1.8.3

### ISSUE THREAD

**Issue by MastaC729** [chylex/Hardcore-Ender-Expansion#137]
Someone was flying around the end in our server, and the following serverside crash happened:

http://pastebin.com/3m4qM1vs

Not sure how to reproduce this, nor am I sure what could have caused it based on the stacktrace. Hope this helps, and let me know if I need to provide any more information.

**Comment by chylex** [comment]
Sorry, can't fix that one because of some weirdness in vanilla code and inability to reliably reproduce the issue. HEE 2 will not have the problem, but for now just restarting the server will load the world fine, it probably won't happen again because it seems really random and rare, but I can't fully guarantee anything.
