### ISSUE TITLE
HHE Exploring The end crash

### ISSUE THREAD

**Issue by Chessus** [chylex/Hardcore-Ender-Expansion#155]
http://paste.feed-the-beast.com/view/7d878fc1

Hi! I've gotten game crashes when exploring the end. Not too sure what to do about it.Is this common?Any help will be appreciated thanks!

**Comment by chylex** [comment]
Sadly I have no idea what's causing it, the mod uses vanilla worldgen system which doesn't work quite well. If you open the world again, the issue should not happen again [unless you are really unlucky], which makes it even harder to find because it just disappears :/.

HEE 2 is going to have a completely different worldgen system which will not have the issue, but it cannot be ported back.

If you still have issues after going back, or experience the issue again at a later point, please reopen the issue (or if you manage to reliably replicate the issue on a world).

**Comment by Chessus** [comment]
That's a shame. I can replicate it but not reliably. Though as you've said, only with generating new areas of the end which isn't always reliable but I can say with certainty it will occur again. I think i'll just wait for HHE 2. Any eta on it? Thanks again.

**Comment by chylex** [comment]
Not this year :/

**Comment by chylex** [comment]
Okay, I *might* have fixed it in the latest version. By fixed, I mean I added a really ugly workaround that might still have issues, and will definitely cause some weirdness (empty chunks), but it should hopefully no longer crash.

**Comment by Chessus** [comment]
I think it's fixed, havn' thad issue since that version :D
