### ISSUE TITLE
scorching pickaxe issue

### ISSUE THREAD

**Issue by Solus-Prime** [chylex/Hardcore-Ender-Expansion#167]
when the scorching pickaxe is used on certain ores such as iron or endium it fills my inventory with stacks of the smelted ore and there tends to be an even larger number of the smelted ore dropped i'm not sure if this was intentional or a bug

**Comment by EmberQuill** [comment]
Chylex, I started doing a binary search like you mentioned in IRC, but ran into a bit of a problem. The bug doesn't occur reliably. Once it starts dropping huge amounts of ingots, it keeps doing so, but actually getting it to start is a challenge. The first time I tried it, it started happening after I mined around a stack each of iron and gold ore. The second time I tried it in a new test world with the same mod setup, I mined enough to break two pickaxes and it never happened at all. I can't do a binary search if I can't reliably duplicate the bug.

**Comment by chylex** [comment]
The pickaxe doesn't have any state, all calculations are done fresh for every mined block... Send me the mods and configs please, I'll have to try custom builds to debug it.

**Comment by EmberQuill** [comment]
I managed to reproduce it again. New Resonant Rise 3.3.0.0 instance, no optional mods selected except for HEE. I didn't change any configs. I made a superflat test world and cheated in a golden pickaxe and a stack of Infernium. Crafted the pick, placed an iron ore and mined it up. Boom, stacks upon stacks of ingots.

**Comment by chylex** [comment]
Some mod is changing the smelting xp values for ores to random numbers, sometimes including 100 which is not allowed by vanilla standard (only values allowed are between 0 and 1). One problem is that vanilla doesn't check the values when they're added, but that's not my problem either.

Sadly it might take time to find the mod due to the randomness, but feel free to yell at them as loudly as you want once you find it.

**Comment by Solus-Prime** [comment]
heres my mod list and configs to try and help narrow it down
https://docs.google.com/spreadsheets/d/1ZgCb1_Za9VV4RxJWIWB92szbtQQGEJh1HglsEe3eIHA/edit?usp=sharing mod list

http://karuta.luminousvector.com/index.php/s/mZWTQmF8vvO4oXO configs

**Comment by EmberQuill** [comment]
@Solus-Prime Technomancy is the culprit. Apparently it sets smelting xp values to 100 for some reason.

**Comment by Mordenkainen** [comment]
Thanks for identifying the source of the issue. It's unfortunate that MC doesn't raise an exception on invalid values.

It was unpredictable because of a flaw in how MC handles the lookup of smelting experience. You can register the same result for multiple furnace recipes, with different experience values. When you request the XP by result, it returns the first one that it finds that matches the result. Since the data is stored in a map, the actual entry returned may vary iteration to iteration.

Essentially this means that mods may not reliably add new smelting recipes for an existing output with a different XP value. Sometimes it will work, and sometimes it wont...
