### ISSUE TITLE
Adding a configuration option to disable key conflicts notifications

### ISSUE THREAD

**Issue by xJon** [chylex/Hardcore-Ender-Expansion#169]
Is it possible? The messages can sometimes be annoying, as they repeat themselves.
![image](https://cloud.githubusercontent.com/assets/8945347/13250329/1a8f1f70-da32-11e5-87f6-1179ad0568f9.png)

**Comment by chylex** [comment]
Perhaps instead of adding a workaround for an issue, it would be better to fix the issue it's reporting.

**Comment by xJon** [comment]
With big modpacks by default it's just too much to find the exact key for this. We prefer the player to pick the free key which is the most comfortable for him, or use MineMenu.
That's why I'd just prefer the message to not appear everytime :)

**Comment by chylex** [comment]
It only appears if there is an actual conflict, which creates issues because Minecraft does not handle conflicting keybindings - one of the binds will not work. If the player is supposed to choose their own keybindings, they should see the message to know the conflict exists. If this is bothering you during testing, use your own config file that will only be in your Minecraft instance and won't be shipped with the modpack.

**Comment by xJon** [comment]
Thing is, to be realistic, if for every key conflict there would be a notification when the player starts the game, the chat will be flooded. And unfortunately this is unavoidable when enough mods are installed.

The players are aware to the conflicts when they open the controls menu and see their wanted button in red. The notification is just a bit out of place, and I figured I could suggest adding an option to disable it, that's all. Thanks anyway for the quick feedback

**Comment by chylex** [comment]
The problem is that without a notification, when HEE prompts you to press the key during in-game events, if there is a conflict it usually doesn't respond.
