### ISSUE TITLE
[1.7-test] Review

### ISSUE THREAD

**Issue by Yulife** [chylex/Hardcore-Ender-Expansion#90]
So... I geared up [pretty well](http://puu.sh/eo7f9/a67e43a06e.png) and went into the end.
Everything started normal, the dragon spawned, hit the crystals with the bow and so on.
The dragon hits quite hard, especially the poison. Something I have noticed as well is that you get struck by lightning every second which gets very annoying and distracting.
The killing of the dragon finally came near and a lot of Dragon Essence and XP dropped. Could retrieve the egg normal with a stone sword.
One thing I noticed, the Endermen do not flee from Primal Orbs from Thaumcraft 4, not sure if this is intended or not.
Wandered around, found a Teleporation B~~e~~acon and that seemed pretty nifty! Is it normal that you cannot break them?
Found an Enderman Tower and again, the Angry Endermen and the Boss can be hit by the Primal Orbs, especially the Boss who reflects ALL projectiles.
Flying through the void I found one of those purple enchanted islands which have a Labotary Building on them. The mages seem a bit... weak. They move very slowly and attack only every 4-5 seconds which is a period of time a player can easily kill it. I would make them more dangerous. All in the all the island seems very.. easy. Personally, I would like it to be more of a challenge. Especially with that loot.
Alright, just found one of these scorching islands. Boy, are they tough! These little buggers hit quite hard, especially those Scorching Lensis that burst over you with fire sparks.
While hasting around, I find that those towers appear very commonly. In my opinion they need to be a bit turned down in terms of spawning.
After a while I finally saw the Infested Forest Island. Kinda spooky, huh? I noticed a bit of a FPS drop, perhaps because of the leaves. The Ravaged Brick seems very tough to break. However, there are sometimes monster spawners imbued in the wall that can be easily broken and players with Morph could easily get through, just a heads up. Also, the ravaged bricks can be replaced by the Focus of Equal Trades. When I got into the dungeon, I noticed that the leeches hardly drop Runes. I am not sure if they are supposed to be a **super** rare drop but even with a Looting V swords around 40 leeches they dropped single rune.
I found another Enchanted Island that seemed to be Homelanded and I found these floating cubes that drop Arcane Shards. I get hit pretty hard by the Homeland Endermen that follow me.
Reading through the Compendium I noticed that the scrolling via mouse is not working. Not sure if this is my problem or not but it is not working for me. Also, I think paying knowledge fragments for the **whole** research would be much more nicer as unlocking every single fragment and recipe is quite.. picky.
I found no generation errors. Though, I found a ton of Ender Lilies but I think that is intended generation. Using BoP no biome conflicts are happening. And.. so.. much.. bacon!
That's it for my testing. I'm tired and I will go to bed now. Hoped it was helpful @chylex! :)

**Comment by chylex** [comment]
I will write down full response when I return from school, kind of in a hurry now.

Thanks for the testing <3

Lightning is probably caused by one of the special attacks, normally it spawns Endermen (with lightning) that start attacking you but if you're flying, it would be pointless so it strikes you instead.

Transport Beacon cannot be picked up or broken, you can try doing stuff with another mods and see if anything works - please let me know then.

Ravaged Bricks are tough, but aren't supposed to be unbreakable. Breaking spawners makes them weaker. Rune drops are affected by the amount of Lice nearby, not exactly sure how that went... and not sure how Looting affects it, will check.

Scrolling in Compendium should work, you are not the first person to have problems with it though. Without any object open, you should scroll everything; and if you open something, left side of the screen will scroll objects, and right side will scroll pages. If you were doing that, well I will need to figure out why it doesn't work >.>

Balancing stages is planned, I didn't have enough time to fully review every aspect of the mod. Mages will be harder >:D

Also, I completely forgot - there's a new config option that lets you override other mods generating in the End, please try that and see if only HEE things spawn.

**Comment by chylex** [comment]
Not sure what the Primal Orb does, but Angry Endermen will not stop attacking you if they get damaged. The Ender Eye should only allow strong melee, again not sure what Primal Orb is so I don't know why it would not ignore it.

The towers eventually spawn less and less often, they should be pretty common in the beginning and when you get to a certain point (couple thousand blocks away from the center), they should be pretty rare.

If you're not sure, try to find the other variation of Infested Forest, it has a huge amount of trees with massive density, so if that doesn't hit your fps even more, it might have been something else...

I can add features to the Compendium to unlock all fragments, it might be tricky because some fragments have special conditions to be unlocked. Might be worth knowing whether the prices are fine, you should be able to get most fragments just fine using points from discovering objects and Knowledge Notes. There's a little bit of micro-managing going on.

Ender Lilies are not from HEE, just making sure you know that. Might be able to find a way of limiting their spawning since I add infinitely explorable space.

**Comment by Yulife** [comment]
Ah, thanks for the feedback. Primal Orbs are the rainbow clusters that come out of the Primal Focus of Thaumcraft 4 and they explode and cause big damage.

**Comment by chylex** [comment]
Alright. If you do more testing (plenty of time left :P), focus on the stuff I described, and try using the different blocks and items (just spawn them in and do stuff that you think might break it).

**Comment by chylex** [comment]
@Yulife Any updates? Did you also try mounting different entities with the dragon (horses, minecarts, planes, brooms, anything you can think of).

**Comment by Yulife** [comment]
Mount? What..

**Comment by chylex** [comment]
Anything you can ride. Need to see if the collisions work with mountable entities.

**Comment by Yulife** [comment]
You mean the knockback of the Ender Dragon?

**Comment by chylex** [comment]
Yes.

**Comment by chylex** [comment]
I can test vanilla stuff myself, but I don't know how modded entities would react (including modded things that replace vanilla entities, like one of the minecart mods).

**Comment by chylex** [comment]
I think that the Compendium scrolling is caused by another mod, which steals the mouse input information so HEE can't handle it. Can you try it again and then start removing mods (just remove a bunch of mods at a time, and once it starts working put only those in)? Then I might be able to see what that mod does and steal the input back.

**Comment by Yulife** [comment]
Aight. A little bit busy with RL atm.

**Comment by Yulife** [comment]
TF's Pincher Bugs work normal.
Seats from Bibliocraft leave you floating and sitting if the Ender Dragon destroys them. No knockback.

**Comment by chylex** [comment]
What are Pincher Bugs?

**Comment by Yulife** [comment]
[These bastards.](http://puu.sh/eBiL5/c5456b8515.jpg)

**Comment by chylex** [comment]
Guessing they pick you up? :P

**Comment by Yulife** [comment]
Yes.
